server:
  port: 8000

spring:
  servlet:
    multipart:
      max-file-size: 10MB         # 총 파일의 최대 사이즈
      max-request-size: 10MB      # request(요청) 최대 사이즈

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html